import type { CaseDefinition } from "../game/types";

export const lacquerBoxCase = {
  id: "lacquer-box-001",
  title: "民国漆木首饰盒",
  seller: {
    name: "刘先生",
    summary: "急于出售，但对器物经历有所保留",
    openingPrice: 80,
  },
  actionBudget: 6,
  seed: 20260723,
  suggestedDiscount: 60,
  claims: [
    { id: "claim-inherited", text: "这是家里祖传下来的。", topic: "来源" },
    {
      id: "claim-never-restored",
      text: "这件东西从来没有修过。",
      topic: "修复历史",
    },
    {
      id: "claim-price",
      text: "这种老东西现在很少见，八十点不算高。",
      topic: "开价依据",
    },
  ],
  initialNpcState: {
    pressure: 26,
    trust: 58,
    dealIntent: 72,
    control: 68,
    phase: "relaxed",
  },
  npcProfile: {
    id: "family-resale-uncertain",
    label: "把家中旧物当普通老盒出售",
    beliefSummary: "卖家知道来源说法并不严谨，也不确定是否维修过，但不知道器物的客观真伪与准确价值。",
    reservationPrice: 55,
  },
  truthVariants: {
    counterfeit: {
      id: "counterfeit",
      label: "现代仿制品",
      summary: "木胎、漆层、五金与做旧痕迹均为现代制作。",
      trueValue: 20,
      facts: [
        "木胎为现代机制板材",
        "漆层使用人工做旧工艺",
        "锁扣与底款均为现代仿制",
        "人工磨损与材料自然老化不相符",
      ],
    },
    "restored-genuine": {
      id: "restored-genuine",
      label: "旧胎重修真品",
      summary: "主体为民国晚期旧物，但经历现代翻修、后配与后刻。",
      trueValue: 65,
      facts: [
        "木胎为民国晚期旧物",
        "表面经过现代翻修",
        "锁扣后配，底款后刻",
        "内部氧化层早于表面翻修层",
      ],
    },
    "hidden-treasure": {
      id: "hidden-treasure",
      label: "被低估的珍品",
      summary: "器物整体年代、工艺与款识能够互相印证，保存状态罕见。",
      trueValue: 130,
      facts: [
        "木胎与漆层均符合清末至民国早期工艺",
        "接口使用老化动物胶，未见现代拆修",
        "锁扣和底款与器物年代一致",
        "榫接记号与地方作坊款识能够互相印证",
      ],
    },
  },
  evidence: {
    "counterfeit-surface": {
      id: "counterfeit-surface",
      name: "规律做旧裂纹",
      kind: "object",
      topic: "漆面年代",
      strength: "medium",
      detail: "裂纹粗细与间距过于均匀，边缘没有长期积尘。",
      inference: "可能是现代人工制造的老化外观。",
      lead: "做旧常在边缘、底部与内腔留下不一致，可继续对照。",
      likelihoods: { counterfeit: 0.78, "restored-genuine": 0.17, "hidden-treasure": 0.05 },
    },
    "restored-surface": {
      id: "restored-surface",
      name: "新旧漆层断差",
      kind: "object",
      topic: "修复历史",
      strength: "weak",
      detail: "主体漆层有旧裂纹，局部光泽却更亮、更连续。",
      inference: "旧胎上可能存在较新的罩漆或补漆。",
      lead: "后期处理容易在接口和五金附近留下更明确的边界。",
      likelihoods: { counterfeit: 0.2, "restored-genuine": 0.65, "hidden-treasure": 0.15 },
    },
    "treasure-surface": {
      id: "treasure-surface",
      name: "自然漆面断纹",
      kind: "object",
      topic: "漆面年代",
      strength: "medium",
      detail: "断纹不规则，积尘、磨损与木胎收缩方向一致。",
      inference: "漆面与木胎可能经历了相近的自然老化。",
      lead: "若底款、接口和五金也能相互印证，整体年代判断会更稳。",
      likelihoods: { counterfeit: 0.05, "restored-genuine": 0.18, "hidden-treasure": 0.77 },
    },
    "counterfeit-bottom": {
      id: "counterfeit-bottom",
      name: "电动刻款痕",
      kind: "object",
      topic: "来源",
      strength: "strong",
      detail: "底款转角圆滑，沟底留有高速旋转工具的连续纹路。",
      inference: "款识很可能是现代工具仿刻。",
      lead: "若内腔也出现机制加工痕迹，现代仿制的解释会更完整。",
      likelihoods: { counterfeit: 0.9, "restored-genuine": 0.08, "hidden-treasure": 0.02 },
    },
    "restored-bottom": {
      id: "restored-bottom",
      name: "后刻底款",
      kind: "object",
      topic: "来源",
      strength: "strong",
      detail: "底款切口锐利，沟内磨损明显少于周围木胎。",
      inference: "旧胎是真，但款识很可能后加，不能据此抬高价值。",
      lead: "对照内腔木胎和锁扣年代，可以判断是旧物重修还是整体仿制。",
      likelihoods: { counterfeit: 0.25, "restored-genuine": 0.7, "hidden-treasure": 0.05 },
    },
    "treasure-bottom": {
      id: "treasure-bottom",
      name: "旧款与磨损同层",
      kind: "object",
      topic: "来源",
      strength: "strong",
      detail: "款识沟内积尘、氧化与底部磨损连续，没有后刻断差。",
      inference: "底款与器物可能处于同一历史层。",
      lead: "继续验证木胎工具痕和五金，能够排除旧款新器的可能。",
      likelihoods: { counterfeit: 0.03, "restored-genuine": 0.12, "hidden-treasure": 0.85 },
    },
    "counterfeit-joint": {
      id: "counterfeit-joint",
      name: "新工业胶层",
      kind: "object",
      topic: "修复历史",
      strength: "strong",
      detail: "接口胶层完整、透明，木胎两侧都没有旧胶残留。",
      inference: "器物可能从制作时就使用现代胶黏剂。",
      lead: "现代胶并不单独证明整体仿制，还需要核对木胎和五金。",
      contradicts: "claim-never-restored",
      likelihoods: { counterfeit: 0.55, "restored-genuine": 0.43, "hidden-treasure": 0.02 },
    },
    "modern-adhesive-trace": {
      id: "modern-adhesive-trace",
      name: "现代胶痕",
      kind: "object",
      topic: "修复历史",
      strength: "strong",
      detail: "接口残留的透明胶体形态与旧漆层不一致。",
      inference: "支持近现代拆修，但尚不能证明木胎本身为新作。",
      lead: "检查内腔木胎与锁扣年代，可以区分旧物重修和整体仿制。",
      contradicts: "claim-never-restored",
      likelihoods: { counterfeit: 0.4, "restored-genuine": 0.58, "hidden-treasure": 0.02 },
    },
    "treasure-joint": {
      id: "treasure-joint",
      name: "老化动物胶",
      kind: "object",
      topic: "修复历史",
      strength: "medium",
      detail: "胶层发暗且脆化，积尘与接口磨损连续。",
      inference: "接口未见明显现代拆修，胶层年代与器物较一致。",
      lead: "仍需查看锁扣是否后配，以及底款能否互相印证。",
      likelihoods: { counterfeit: 0.04, "restored-genuine": 0.21, "hidden-treasure": 0.75 },
    },
    "counterfeit-latch": {
      id: "counterfeit-latch",
      name: "批量冲压锁扣",
      kind: "object",
      topic: "五金年代",
      strength: "strong",
      detail: "锁扣背面有统一冲压纹和现代规格螺钉。",
      inference: "五金为现代批量件。",
      lead: "若木胎同样存在机制加工痕迹，整体仿制概率会显著上升。",
      likelihoods: { counterfeit: 0.82, "restored-genuine": 0.16, "hidden-treasure": 0.02 },
    },
    "restored-latch": {
      id: "restored-latch",
      name: "后配锁扣",
      kind: "object",
      topic: "五金年代",
      strength: "medium",
      detail: "锁扣磨损少于箱体，螺孔附近还留有旧孔位。",
      inference: "锁扣经过后配，但不能据此否定木胎年代。",
      lead: "内腔木胎能帮助判断后配发生在旧物上，还是整件器物都很新。",
      likelihoods: { counterfeit: 0.2, "restored-genuine": 0.7, "hidden-treasure": 0.1 },
    },
    "treasure-latch": {
      id: "treasure-latch",
      name: "同期铜锁扣",
      kind: "object",
      topic: "五金年代",
      strength: "strong",
      detail: "铜锈进入螺孔，锁扣磨损方向与箱体开合痕迹一致。",
      inference: "锁扣可能与器物长期共同使用。",
      lead: "若内腔工具痕也符合传统制作，多个年代指标将形成闭环。",
      likelihoods: { counterfeit: 0.03, "restored-genuine": 0.12, "hidden-treasure": 0.85 },
    },
    "counterfeit-interior": {
      id: "counterfeit-interior",
      name: "机制板材边缘",
      kind: "object",
      topic: "木胎年代",
      strength: "anchor",
      detail: "内腔边缘出现均匀层压结构和机器锯切纹。",
      inference: "木胎为现代机制材料，足以锚定整体仿制判断。",
      lead: "已有关键物证，可以直接进入交易，也可询问来源固定卖家陈述。",
      likelihoods: { counterfeit: 0.97, "restored-genuine": 0.02, "hidden-treasure": 0.01 },
    },
    "restored-interior": {
      id: "restored-interior",
      name: "旧木胎氧化层",
      kind: "object",
      topic: "木胎年代",
      strength: "strong",
      detail: "内腔刨痕不规则，木色由表及里逐渐变浅，符合长期氧化。",
      inference: "木胎本身较旧，现代痕迹更可能来自后期修复。",
      lead: "把旧木胎与现代胶痕放在一起，能够支持“旧物重修”的解释。",
      likelihoods: { counterfeit: 0.05, "restored-genuine": 0.82, "hidden-treasure": 0.13 },
    },
    "treasure-interior": {
      id: "treasure-interior",
      name: "地方作坊工具痕",
      kind: "object",
      topic: "木胎年代",
      strength: "anchor",
      detail: "内腔留下成组手工刨削与榫接记号，可与底款对应。",
      inference: "木胎、工艺和款识形成强关联，支持高价值地方作坊判断。",
      lead: "已有关键证据，可以直接决策，也可向卖家追问来源。",
      likelihoods: { counterfeit: 0.01, "restored-genuine": 0.04, "hidden-treasure": 0.95 },
    },
    "counterfeit-bonus": {
      id: "counterfeit-bonus",
      name: "板材生产批号",
      kind: "object",
      topic: "木胎年代",
      strength: "anchor",
      detail: "内侧隐蔽处残留现代板材批号。",
      inference: "直接把制作年代锁定在现代。",
      lead: "关键证据已经出现，可以直接处置或固定卖家陈述。",
      likelihoods: { counterfeit: 0.99, "restored-genuine": 0.005, "hidden-treasure": 0.005 },
    },
    "restored-bonus": {
      id: "restored-bonus",
      name: "维修日期铅笔记",
      kind: "object",
      topic: "修复历史",
      strength: "anchor",
      detail: "锁扣内侧可见“2004”铅笔记号，与新胶层位置一致。",
      inference: "旧胎在近现代维修的时间获得直接锚点。",
      lead: "木胎年代仍需单独判断，但修复事实已经可以确认。",
      likelihoods: { counterfeit: 0.08, "restored-genuine": 0.9, "hidden-treasure": 0.02 },
    },
    "treasure-bonus": {
      id: "treasure-bonus",
      name: "作坊暗记",
      kind: "object",
      topic: "来源",
      strength: "anchor",
      detail: "底款侧边出现与地方作坊档案一致的隐蔽记号。",
      inference: "来源与工艺得到罕见的直接印证。",
      lead: "关键证据已经出现，可以直接处置或继续确认卖家并不知情。",
      likelihoods: { counterfeit: 0.005, "restored-genuine": 0.015, "hidden-treasure": 0.98 },
    },
    "repair-admission": {
      id: "repair-admission",
      name: "修复说法发生变化",
      kind: "statement",
      topic: "修复历史",
      strength: "medium",
      detail: "卖家从“从未修过”收窄为“接手后没有修过”。",
      inference: "原陈述不完整，修复风险与来源链都需要继续核验。",
      lead: "可继续检查木胎，或追问父辈购买时间。",
      contradicts: "claim-never-restored",
      likelihoods: { counterfeit: 0.34, "restored-genuine": 0.56, "hidden-treasure": 0.1 },
    },
    "test-modern-adhesive": {
      id: "test-modern-adhesive",
      name: "检测：合成胶黏剂",
      kind: "test",
      topic: "修复历史",
      strength: "anchor",
      detail: "专项检测确认接口含近现代合成胶成分。",
      inference: "近现代制作或修复确定存在，但检测没有回答木胎本身年代。",
      lead: "结合木胎和五金证据才能区分整体仿制与旧物重修。",
      likelihoods: { counterfeit: 0.43, "restored-genuine": 0.56, "hidden-treasure": 0.01 },
    },
    "test-old-organic-adhesive": {
      id: "test-old-organic-adhesive",
      name: "检测：老化动物胶",
      kind: "test",
      topic: "修复历史",
      strength: "anchor",
      detail: "专项检测显示胶层为长期老化的动物胶，未检出合成胶。",
      inference: "接口年代较早，但仍不能单凭胶层确认底款和整体价值。",
      lead: "底款、木胎工艺与五金仍需互相印证。",
      likelihoods: { counterfeit: 0.02, "restored-genuine": 0.18, "hidden-treasure": 0.8 },
    },
  },
  observationTargets: [
    {
      id: "surface",
      label: "漆面",
      short: "观察裂纹、光泽与磨损",
      knowledgeHint: "先区分自然老化与人工做旧，再寻找新旧层断差。",
      results: {
        counterfeit: { evidenceId: "counterfeit-surface", title: "漆面裂纹过于整齐", description: "你记录下裂纹间距和积尘不一致。", bonusEvidenceId: "counterfeit-bonus", bonusChance: 0.12 },
        "restored-genuine": { evidenceId: "restored-surface", title: "漆面出现新旧断差", description: "旧裂纹之上有局部连续亮层。", bonusEvidenceId: "restored-bonus", bonusChance: 0.12 },
        "hidden-treasure": { evidenceId: "treasure-surface", title: "老化痕迹彼此一致", description: "裂纹、积尘和木胎收缩方向能够对应。", bonusEvidenceId: "treasure-bonus", bonusChance: 0.12 },
      },
    },
    {
      id: "bottom",
      label: "底部",
      short: "查看底款与底部磨损",
      knowledgeHint: "款识沟内的磨损和积尘，应与周围历史层连续。",
      results: {
        counterfeit: { evidenceId: "counterfeit-bottom", title: "底款留下电动工具痕", description: "沟底纹路连续，转角不符合手工刻制。", bonusEvidenceId: "counterfeit-bonus", bonusChance: 0.18 },
        "restored-genuine": { evidenceId: "restored-bottom", title: "底款可能后刻", description: "款识切口比周围木胎新得多。", bonusEvidenceId: "restored-bonus", bonusChance: 0.18 },
        "hidden-treasure": { evidenceId: "treasure-bottom", title: "底款与磨损处于同一层", description: "沟内外的积尘和氧化连续。", bonusEvidenceId: "treasure-bonus", bonusChance: 0.18 },
      },
    },
    {
      id: "joint",
      label: "接口",
      short: "检查拼接与胶层",
      knowledgeHint: "胶层只能回答制作或修复时间，不能单独决定整件器物真伪。",
      results: {
        counterfeit: { evidenceId: "counterfeit-joint", title: "接口使用现代工业胶", description: "胶层完整，未见旧胶痕迹。", bonusEvidenceId: "counterfeit-bonus", bonusChance: 0.15 },
        "restored-genuine": { evidenceId: "modern-adhesive-trace", title: "发现现代胶痕", description: "透明胶体与旧漆层不一致。", bonusEvidenceId: "restored-bonus", bonusChance: 0.15 },
        "hidden-treasure": { evidenceId: "treasure-joint", title: "接口保留老化动物胶", description: "胶层、积尘和磨损连续。", bonusEvidenceId: "treasure-bonus", bonusChance: 0.15 },
      },
    },
    {
      id: "latch",
      label: "锁扣",
      short: "核对五金与孔位",
      knowledgeHint: "后配五金会留下旧孔位或磨损断层，但旧物后配不等于整体赝品。",
      results: {
        counterfeit: { evidenceId: "counterfeit-latch", title: "锁扣是现代批量件", description: "冲压纹和螺钉规格都很统一。", bonusEvidenceId: "counterfeit-bonus", bonusChance: 0.18 },
        "restored-genuine": { evidenceId: "restored-latch", title: "锁扣经过后配", description: "新孔位旁保留了旧孔。", bonusEvidenceId: "restored-bonus", bonusChance: 0.18 },
        "hidden-treasure": { evidenceId: "treasure-latch", title: "锁扣磨损与箱体一致", description: "铜锈进入螺孔，开合痕迹能够对应。", bonusEvidenceId: "treasure-bonus", bonusChance: 0.18 },
      },
    },
    {
      id: "interior",
      label: "内腔",
      short: "查看木胎与工具痕",
      knowledgeHint: "木胎结构通常比表面装饰更难伪装，是区分旧胎重修与整体仿制的重要位置。",
      results: {
        counterfeit: { evidenceId: "counterfeit-interior", title: "发现现代机制板材", description: "层压结构和机器锯切纹足以锚定现代制作。", bonusEvidenceId: "counterfeit-bonus", bonusChance: 0.2 },
        "restored-genuine": { evidenceId: "restored-interior", title: "木胎具有长期氧化", description: "不规则刨痕和渐变木色支持旧胎判断。", bonusEvidenceId: "restored-bonus", bonusChance: 0.2 },
        "hidden-treasure": { evidenceId: "treasure-interior", title: "工具痕对应地方作坊", description: "榫接记号与底款能够互相印证。", bonusEvidenceId: "treasure-bonus", bonusChance: 0.2 },
      },
    },
  ],
  dialogueTopics: [
    {
      id: "repair-history",
      label: "修复历史",
      evidenceTopics: ["修复历史"],
      prompt: "这件东西过去是否维修、换件或重新上漆？",
      initialClaim: "这件东西从来没有修过。",
      responseEvidenceId: "repair-admission",
      responses: {
        cooperate: "我父亲买来时可能收拾过，我接手以后没有再修。",
        deflect: "至少我接手以后没有修过，之前的事情我不清楚。",
        "partial-admit": "锁扣可能换过，表面以前也许重新处理过。",
        counter: "旧东西修过很正常，你不能因此把它全盘否定。",
        refuse: "我能说的都说了，再问也是这些。",
        exit: "你这么不信任我，这东西我不卖了。",
      },
      signals: {
        cooperate: {
          id: "repair:uncertain-history",
          label: "卖家承认早期维修史不确定",
          likelihoods: { counterfeit: 0.3, "restored-genuine": 0.52, "hidden-treasure": 0.18 },
        },
        deflect: {
          id: "repair:limited-knowledge",
          label: "卖家只确认自己接手后的情况",
          likelihoods: { counterfeit: 0.36, "restored-genuine": 0.46, "hidden-treasure": 0.18 },
        },
        "partial-admit": {
          id: "repair:possible-rework",
          label: "卖家收窄为可能换件或重做表面",
          likelihoods: { counterfeit: 0.3, "restored-genuine": 0.6, "hidden-treasure": 0.1 },
        },
        counter: {
          id: "repair:normalization",
          label: "卖家强调修过不等于赝品",
          likelihoods: { counterfeit: 0.3, "restored-genuine": 0.48, "hidden-treasure": 0.22 },
        },
        refuse: {
          id: "repair:refusal",
          label: "卖家拒绝继续解释维修史",
          likelihoods: { counterfeit: 0.39, "restored-genuine": 0.42, "hidden-treasure": 0.19 },
        },
        exit: {
          id: "repair:exit",
          label: "卖家因维修质疑离场",
          likelihoods: { counterfeit: 0.36, "restored-genuine": 0.4, "hidden-treasure": 0.24 },
        },
      },
    },
    {
      id: "provenance",
      label: "来源经历",
      evidenceTopics: ["来源"],
      prompt: "它最早从哪里得到，有没有票据或家族记录？",
      initialClaim: "这是家里祖传下来的。",
      responses: {
        cooperate: "父亲大概九十年代从旧货市场买的，票据早找不到了。",
        deflect: "是父亲留下的，我一直习惯说成家里传下来的。",
        "partial-admit": "严格说不是祖传，是父亲后来买回家的。",
        counter: "在家里放了几十年，说家传也没有恶意。",
        refuse: "父亲已经不在了，我没法再证明。",
        exit: "非要票据才谈，那就算了。",
      },
      signals: {
        cooperate: {
          id: "provenance:market-1990s",
          label: "来源收窄为九十年代旧货市场",
          likelihoods: { counterfeit: 0.2, "restored-genuine": 0.62, "hidden-treasure": 0.18 },
        },
        deflect: {
          id: "provenance:family-shorthand",
          label: "卖家把父辈购入简化成家传",
          likelihoods: { counterfeit: 0.28, "restored-genuine": 0.5, "hidden-treasure": 0.22 },
        },
        "partial-admit": {
          id: "provenance:not-ancestral",
          label: "卖家承认并非严格祖传",
          likelihoods: { counterfeit: 0.32, "restored-genuine": 0.56, "hidden-treasure": 0.12 },
        },
        counter: {
          id: "provenance:no-paperwork",
          label: "卖家以持有年限替代来源证明",
          likelihoods: { counterfeit: 0.33, "restored-genuine": 0.4, "hidden-treasure": 0.27 },
        },
        refuse: {
          id: "provenance:refusal",
          label: "卖家无法继续补足来源链",
          likelihoods: { counterfeit: 0.4, "restored-genuine": 0.4, "hidden-treasure": 0.2 },
        },
        exit: {
          id: "provenance:exit",
          label: "卖家因来源追问离场",
          likelihoods: { counterfeit: 0.37, "restored-genuine": 0.39, "hidden-treasure": 0.24 },
        },
      },
    },
    {
      id: "price",
      label: "开价依据",
      evidenceTopics: ["开价依据", "修复历史", "来源", "木胎年代", "五金年代", "漆面年代"],
      prompt: "八十价值点的开价依据是什么？",
      initialClaim: "这种老东西现在很少见，八十点不算高。",
      responses: {
        cooperate: "我参考了几件类似旧盒，但没有把修补单独算进去。",
        deflect: "旧木胎和漆工都值钱，八十只是开价。",
        "partial-admit": "如果修补确实比较多，价格可以重新谈。",
        counter: "修过也不代表没有价值。",
        refuse: "价格只在诚心买的前提下谈。",
        exit: "你只想压价，这单不做了。",
      },
      signals: {
        cooperate: {
          id: "price:rough-comparison",
          label: "开价来自粗略同类比较",
          likelihoods: { counterfeit: 0.31, "restored-genuine": 0.46, "hidden-treasure": 0.23 },
        },
        deflect: {
          id: "price:generic-old-value",
          label: "卖家以一般旧物价值支撑开价",
          likelihoods: { counterfeit: 0.34, "restored-genuine": 0.43, "hidden-treasure": 0.23 },
        },
        "partial-admit": {
          id: "price:repair-negotiable",
          label: "卖家承认修补可成为议价依据",
          likelihoods: { counterfeit: 0.3, "restored-genuine": 0.55, "hidden-treasure": 0.15 },
        },
        counter: {
          id: "price:repair-not-fake",
          label: "卖家区分修补与整体真伪",
          likelihoods: { counterfeit: 0.28, "restored-genuine": 0.5, "hidden-treasure": 0.22 },
        },
        refuse: {
          id: "price:refusal",
          label: "卖家拒绝继续解释价格",
          likelihoods: { counterfeit: 0.36, "restored-genuine": 0.4, "hidden-treasure": 0.24 },
        },
        exit: {
          id: "price:exit",
          label: "卖家因压价离场",
          likelihoods: { counterfeit: 0.34, "restored-genuine": 0.4, "hidden-treasure": 0.26 },
        },
      },
    },
  ],
  knowledgeCards: [
    {
      id: "knowledge-aging",
      title: "老化不是一种纹理",
      body: "自然老化通常会让裂纹、积尘、磨损与材料收缩彼此对应；人工做旧容易只复制表面图案。",
    },
    {
      id: "knowledge-repair",
      title: "修补与真伪要分开",
      body: "现代胶、后配五金可以证明后期处理，却不能单独证明旧木胎也是现代制作。",
    },
    {
      id: "knowledge-provenance",
      title: "来源需要交叉验证",
      body: "口述来源应与票据、旧照片、款识年代和器物本身互相印证；“家里留下”不等于严格的祖传。",
    },
  ],
  test: {
    id: "adhesive-test",
    label: "胶层成分专项检测",
    description: "只回答胶层成分与大致时代，不直接鉴定整件器物。",
    actionPointCost: 2,
    valueCost: 10,
    evidenceByVariant: {
      counterfeit: "test-modern-adhesive",
      "restored-genuine": "test-modern-adhesive",
      "hidden-treasure": "test-old-organic-adhesive",
    },
  },
} satisfies CaseDefinition;

export type LacquerBoxCase = typeof lacquerBoxCase;
